#!/usr/bin/python3

from plano import *

# Set this to change the default broker port
# ENV["MESSAGING_SERVICE_PORT"] = "5672"

# enable_logging(level="warn")

frontend = None
backend = None

try:
    with working_env(HTTP_HOST="localhost", HTTP_PORT="8081", JAEGER_SAMPLER_TYPE="const", JAEGER_SAMPLER_PARAM="1"):
        frontend = start_process("java -jar frontends/java/target/careful-soup-frontend-1.0.0-SNAPSHOT-jar-with-dependencies.jar")

    backend = start_process("python3 backends/python/app.py")

    while True:
        try:
            http_get("http://localhost:8081/api/ready")
            break
        except CalledProcessError:
            sleep(0.2)

    call(f"curl -fX POST -d \"hello 1\" -H \"jaeger-debug-id: {get_unique_id()}\" -H \"Content-type: text/plain\" http://localhost:8081/api/send-request")
    call(f"curl -fX POST -d \"hello 2\" -H \"jaeger-debug-id: {get_unique_id()}\" -H \"Content-type: text/plain\" http://localhost:8081/api/send-request")
    call(f"curl -fX POST -d \"hello 3\" -H \"jaeger-debug-id: {get_unique_id()}\" -H \"Content-type: text/plain\" http://localhost:8081/api/send-request")

finally:
    terminate_process(frontend)
    terminate_process(backend)
